// Complete NAQ Questionnaire Data - 321 questions
// Based on "Signs and Symptoms Analysis from a Functional Perspective" by Dicken Weatherby, N.D.

export interface NAQQuestion {
  question_text: string;
  section: string;
  category: string;
  order_index: number;
  question_type: string;
  options?: string[];
  is_required: boolean;
}

export const NAQ_COMPLETE_QUESTIONS: NAQQuestion[] = [
  // PART I - Nutrition Analysis (Questions 1-20)
  { question_text: "Alkohol", section: "Analiza prehrane", category: "nutrition", order_index: 1, question_type: "scale_0_3", is_required: true },
  { question_text: "Umjetna sladila", section: "Analiza prehrane", category: "nutrition", order_index: 2, question_type: "scale_0_3", is_required: true },
  { question_text: "Slatkiši, deserti, rafinirani šećer", section: "Analiza prehrane", category: "nutrition", order_index: 3, question_type: "scale_0_3", is_required: true },
  { question_text: "Gazirana pića", section: "Analiza prehrane", category: "nutrition", order_index: 4, question_type: "scale_0_3", is_required: true },
  { question_text: "Duhanski proizvodi za žvakanje", section: "Analiza prehrane", category: "nutrition", order_index: 5, question_type: "scale_0_3", is_required: true },
  { question_text: "Cigarete", section: "Analiza prehrane", category: "nutrition", order_index: 6, question_type: "scale_0_3", is_required: true },
  { question_text: "Cigare/lule", section: "Analiza prehrane", category: "nutrition", order_index: 7, question_type: "scale_0_3", is_required: true },
  { question_text: "Kava i hrana i pića koja sadrže kofein", section: "Analiza prehrane", category: "nutrition", order_index: 8, question_type: "scale_0_3", is_required: true },
  { question_text: "Redovito jedete brzu hranu", section: "Analiza prehrane", category: "nutrition", order_index: 9, question_type: "scale_0_3", is_required: true },
  { question_text: "Pržena hrana", section: "Analiza prehrane", category: "nutrition", order_index: 10, question_type: "scale_0_3", is_required: true },
  { question_text: "Mesne prerađevine", section: "Analiza prehrane", category: "nutrition", order_index: 11, question_type: "scale_0_3", is_required: true },
  { question_text: "Margarin", section: "Analiza prehrane", category: "nutrition", order_index: 12, question_type: "scale_0_3", is_required: true },
  { question_text: "Mliječni proizvodi", section: "Analiza prehrane", category: "nutrition", order_index: 13, question_type: "scale_0_3", is_required: true },
  { question_text: "Izloženost zračenju", section: "Analiza prehrane", category: "nutrition", order_index: 14, question_type: "yes_no", is_required: true },
  { question_text: "Rafinirano brašno/pekarski proizvodi", section: "Analiza prehrane", category: "nutrition", order_index: 15, question_type: "scale_0_3", is_required: true },
  { question_text: "Vitamini i minerali", section: "Analiza prehrane", category: "nutrition", order_index: 16, question_type: "scale_0_3", is_required: true },
  { question_text: "Destilirana voda", section: "Analiza prehrane", category: "nutrition", order_index: 17, question_type: "scale_0_3", is_required: true },
  { question_text: "Voda iz slavine", section: "Analiza prehrane", category: "nutrition", order_index: 18, question_type: "scale_0_3", is_required: true },
  { question_text: "Voda iz bunara", section: "Analiza prehrane", category: "nutrition", order_index: 19, question_type: "scale_0_3", is_required: true },
  { question_text: "Često ste na dijeti radi kontrole težine", section: "Analiza prehrane", category: "nutrition", order_index: 20, question_type: "scale_0_3", is_required: true },

  // PART I - Lifestyle (Questions 21-24)
  { question_text: "Vježbanje tjedno (0=2 ili više puta tjedno, 1=1 put tjedno, 2=1 ili 2 puta mjesečno, 3=nikad)", section: "Životni stil", category: "lifestyle", order_index: 21, question_type: "scale_0_3", is_required: true },
  { question_text: "Promijenili ste posao (0=prije više od 12 mjeseci, 1=unutar 12 mjeseci, 2=unutar 6 mjeseci, 3=unutar 2 mjeseca)", section: "Životni stil", category: "lifestyle", order_index: 22, question_type: "scale_0_3", is_required: true },
  { question_text: "Razvedeni (0=nikad/prije 2+ godine, 1=unutar 2 godine, 2=unutar godine, 3=unutar 6 mjeseci)", section: "Životni stil", category: "lifestyle", order_index: 23, question_type: "scale_0_3", is_required: true },
  { question_text: "Radite više od 60 sati tjedno (0=nikad, 1=povremeno, 2=obično, 3=uvijek)", section: "Životni stil", category: "lifestyle", order_index: 24, question_type: "scale_0_3", is_required: true },

  // PART I - Medications (Questions 25-51)
  { question_text: "Antacidi", section: "Lijekovi", category: "medications", order_index: 25, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi protiv anksioznosti", section: "Lijekovi", category: "medications", order_index: 26, question_type: "yes_no", is_required: false },
  { question_text: "Antibiotici", section: "Lijekovi", category: "medications", order_index: 27, question_type: "yes_no", is_required: false },
  { question_text: "Antikonvulzivi", section: "Lijekovi", category: "medications", order_index: 28, question_type: "yes_no", is_required: false },
  { question_text: "Antidepresivi", section: "Lijekovi", category: "medications", order_index: 29, question_type: "yes_no", is_required: false },
  { question_text: "Antifungici", section: "Lijekovi", category: "medications", order_index: 30, question_type: "yes_no", is_required: false },
  { question_text: "Aspirin/Ibuprofen", section: "Lijekovi", category: "medications", order_index: 31, question_type: "yes_no", is_required: false },
  { question_text: "Inhalatori za astmu", section: "Lijekovi", category: "medications", order_index: 32, question_type: "yes_no", is_required: false },
  { question_text: "Beta blokatori", section: "Lijekovi", category: "medications", order_index: 33, question_type: "yes_no", is_required: false },
  { question_text: "Kontracepcijske pilule/implantati", section: "Lijekovi", category: "medications", order_index: 34, question_type: "yes_no", is_required: false },
  { question_text: "Kemoterapija", section: "Lijekovi", category: "medications", order_index: 35, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi za snižavanje kolesterola", section: "Lijekovi", category: "medications", order_index: 36, question_type: "yes_no", is_required: false },
  { question_text: "Kortizon/steroidi", section: "Lijekovi", category: "medications", order_index: 37, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi za dijabetes/inzulin", section: "Lijekovi", category: "medications", order_index: 38, question_type: "yes_no", is_required: false },
  { question_text: "Diuretici", section: "Lijekovi", category: "medications", order_index: 39, question_type: "yes_no", is_required: false },
  { question_text: "Estrogen ili progesteron (farmaceutski, na recept)", section: "Lijekovi", category: "medications", order_index: 40, question_type: "yes_no", is_required: false },
  { question_text: "Estrogen ili progesteron (prirodni)", section: "Lijekovi", category: "medications", order_index: 41, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi za srce", section: "Lijekovi", category: "medications", order_index: 42, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi za visoki krvni tlak", section: "Lijekovi", category: "medications", order_index: 43, question_type: "yes_no", is_required: false },
  { question_text: "Laksativi", section: "Lijekovi", category: "medications", order_index: 44, question_type: "yes_no", is_required: false },
  { question_text: "Rekreacijske droge", section: "Lijekovi", category: "medications", order_index: 45, question_type: "yes_no", is_required: false },
  { question_text: "Relaksanti/Pilule za spavanje", section: "Lijekovi", category: "medications", order_index: 46, question_type: "yes_no", is_required: false },
  { question_text: "Testosteron (prirodni ili na recept)", section: "Lijekovi", category: "medications", order_index: 47, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi za štitnjaču", section: "Lijekovi", category: "medications", order_index: 48, question_type: "yes_no", is_required: false },
  { question_text: "Acetaminophen (Tylenol)", section: "Lijekovi", category: "medications", order_index: 49, question_type: "yes_no", is_required: false },
  { question_text: "Lijekovi za čir", section: "Lijekovi", category: "medications", order_index: 50, question_type: "yes_no", is_required: false },
  { question_text: "Sildenafil citrat (Viagra)", section: "Lijekovi", category: "medications", order_index: 51, question_type: "yes_no", is_required: false },

  // PART II - Upper GI System (Questions 52-70)
  { question_text: "Podrigivanje ili plinovi unutar jednog sata nakon jela", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 52, question_type: "symptom_0_3", is_required: true },
  { question_text: "Žgaravica ili refluks kiseline", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 53, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nadutost unutar jednog sata nakon jela", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 54, question_type: "symptom_0_3", is_required: true },
  { question_text: "Veganska prehrana (bez mliječnih proizvoda, mesa, ribe ili jaja)", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 55, question_type: "yes_no", is_required: true },
  { question_text: "Loš zadah (halitoza)", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 56, question_type: "symptom_0_3", is_required: true },
  { question_text: "Gubitak okusa za meso", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 57, question_type: "symptom_0_3", is_required: true },
  { question_text: "Znoj ima jak miris", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 58, question_type: "symptom_0_3", is_required: true },
  { question_text: "Želudac uznemiren uzimanjem vitamina", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 59, question_type: "symptom_0_3", is_required: true },
  { question_text: "Osjećaj prekomjerne sitosti nakon jela", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 60, question_type: "symptom_0_3", is_required: true },
  { question_text: "Osjećaj preskakanja doručka", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 61, question_type: "symptom_0_3", is_required: true },
  { question_text: "Osjećaj bolje ako ne jedete", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 62, question_type: "symptom_0_3", is_required: true },
  { question_text: "Pospanost nakon jela", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 63, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nokti se lako lome, ljušte ili pucaju", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 64, question_type: "symptom_0_3", is_required: true },
  { question_text: "Anemija koja ne reaguje na željezo", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 65, question_type: "symptom_0_3", is_required: true },
  { question_text: "Bolovi ili grčevi u želucu", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 66, question_type: "symptom_0_3", is_required: true },
  { question_text: "Proljev, kronični", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 67, question_type: "symptom_0_3", is_required: true },
  { question_text: "Proljev ubrzo nakon jela", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 68, question_type: "symptom_0_3", is_required: true },
  { question_text: "Crna ili katranasta stolica", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 69, question_type: "symptom_0_3", is_required: true },
  { question_text: "Neprobavljena hrana u stolici", section: "Gornji gastrointestinalni sustav", category: "upper_gi", order_index: 70, question_type: "symptom_0_3", is_required: true },

  // Liver and Gallbladder (Questions 71-98, 28 questions)
  { question_text: "Greasy or high fat foods cause distress", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 71, question_type: "symptom_0_3", is_required: true },
  { question_text: "Lower bowel gas several hours after eating", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 72, question_type: "symptom_0_3", is_required: true },
  { question_text: "Undigested fats in stool", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 73, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dry skin and/or hair", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 74, question_type: "symptom_0_3", is_required: true },
  { question_text: "Light or pale colored stools", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 75, question_type: "symptom_0_3", is_required: true },
  { question_text: "Pain between shoulder blades", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 76, question_type: "symptom_0_3", is_required: true },
  { question_text: "History of gallbladder attacks", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 77, question_type: "symptom_0_3", is_required: true },
  { question_text: "Gallbladder removed", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 78, question_type: "yes_no", is_required: true },
  { question_text: "Bitter taste in mouth", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 79, question_type: "symptom_0_3", is_required: true },
  { question_text: "Easily intoxicated if drinking wine", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 80, question_type: "symptom_0_3", is_required: true },
  { question_text: "Headache over eyes", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 81, question_type: "symptom_0_3", is_required: true },
  { question_text: "Hemorrhoids or varicose veins", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 82, question_type: "symptom_0_3", is_required: true },
  { question_text: "History of hepatitis or jaundice", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 83, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nausea", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 84, question_type: "symptom_0_3", is_required: true },
  { question_text: "Motion sickness or sea sickness", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 85, question_type: "symptom_0_3", is_required: true },
  { question_text: "Pain under right side of rib cage", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 86, question_type: "symptom_0_3", is_required: true },
  { question_text: "Stools are often light colored", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 87, question_type: "symptom_0_3", is_required: true },
  { question_text: "Skin has a yellowish cast", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 88, question_type: "symptom_0_3", is_required: true },
  { question_text: "Frequent urination", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 89, question_type: "symptom_0_3", is_required: true },
  { question_text: "Bowel movements often difficult or uncomfortable", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 90, question_type: "symptom_0_3", is_required: true },
  { question_text: "Joint stiffness/pain upon rising but improves during day", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 91, question_type: "symptom_0_3", is_required: true },
  { question_text: "Crave sweets/sugar during day", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 92, question_type: "symptom_0_3", is_required: true },
  { question_text: "Shaky or lightheaded if meals delayed", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 93, question_type: "symptom_0_3", is_required: true },
  { question_text: "Sensitive to chemicals (perfume, cleaning agents, etc.)", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 94, question_type: "symptom_0_3", is_required: true },
  { question_text: "Sensitive to tobacco smoke", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 95, question_type: "symptom_0_3", is_required: true },
  { question_text: "Morning nausea", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 96, question_type: "symptom_0_3", is_required: true },
  { question_text: "Moodiness or depression in morning", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 97, question_type: "symptom_0_3", is_required: true },
  { question_text: "Have taken birth control pills or hormone replacement", section: "Jetra i žučni mjehur", category: "liver_gallbladder", order_index: 98, question_type: "yes_no", is_required: true },

  // Small Intestine (Questions 99-115, 17 questions)
  { question_text: "Airborne allergies/mucus production", section: "Tanko crijevo", category: "small_intestine", order_index: 99, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dairy intolerance (lactose)", section: "Tanko crijevo", category: "small_intestine", order_index: 100, question_type: "symptom_0_3", is_required: true },
  { question_text: "Eczema, hives, rashes, skin irritations", section: "Tanko crijevo", category: "small_intestine", order_index: 101, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive gas production", section: "Tanko crijevo", category: "small_intestine", order_index: 102, question_type: "symptom_0_3", is_required: true },
  { question_text: "Food allergies/intolerances", section: "Tanko crijevo", category: "small_intestine", order_index: 103, question_type: "symptom_0_3", is_required: true },
  { question_text: "Grain intolerance/wheat sensitivity", section: "Tanko crijevo", category: "small_intestine", order_index: 104, question_type: "symptom_0_3", is_required: true },
  { question_text: "Lower bowel gas several hours after eating", section: "Tanko crijevo", category: "small_intestine", order_index: 105, question_type: "symptom_0_3", is_required: true },
  { question_text: "Recurrent sinusitis or sinus infections", section: "Tanko crijevo", category: "small_intestine", order_index: 106, question_type: "symptom_0_3", is_required: true },
  { question_text: "Recurrent bladder or yeast infections", section: "Tanko crijevo", category: "small_intestine", order_index: 107, question_type: "symptom_0_3", is_required: true },
  { question_text: "Abdominal cramps or bloating", section: "Tanko crijevo", category: "small_intestine", order_index: 108, question_type: "symptom_0_3", is_required: true },
  { question_text: "Fibromyalgia or aching in muscles/joints", section: "Tanko crijevo", category: "small_intestine", order_index: 109, question_type: "symptom_0_3", is_required: true },
  { question_text: "Alternating constipation and diarrhea", section: "Tanko crijevo", category: "small_intestine", order_index: 110, question_type: "symptom_0_3", is_required: true },
  { question_text: "Rectal itching", section: "Tanko crijevo", category: "small_intestine", order_index: 111, question_type: "symptom_0_3", is_required: true },
  { question_text: "Leaky gut/Intestinal permeability", section: "Tanko crijevo", category: "small_intestine", order_index: 112, question_type: "symptom_0_3", is_required: true },
  { question_text: "Constipation (less than one bowel movement per day)", section: "Tanko crijevo", category: "small_intestine", order_index: 113, question_type: "symptom_0_3", is_required: true },
  { question_text: "Chronic diarrhea", section: "Tanko crijevo", category: "small_intestine", order_index: 114, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive foul smelling lower bowel gas", section: "Tanko crijevo", category: "small_intestine", order_index: 115, question_type: "symptom_0_3", is_required: true },

  // Large Intestine (Questions 116-135, 20 questions)
  { question_text: "Lower abdominal pain relieved by bowel movements", section: "Debelo crijevo", category: "large_intestine", order_index: 116, question_type: "symptom_0_3", is_required: true },
  { question_text: "Gas shortly after eating", section: "Debelo crijevo", category: "large_intestine", order_index: 117, question_type: "symptom_0_3", is_required: true },
  { question_text: "Pass large amounts of foul smelling gas", section: "Debelo crijevo", category: "large_intestine", order_index: 118, question_type: "symptom_0_3", is_required: true },
  { question_text: "Alternating diarrhea and constipation", section: "Debelo crijevo", category: "large_intestine", order_index: 119, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive mucus in stool", section: "Debelo crijevo", category: "large_intestine", order_index: 120, question_type: "symptom_0_3", is_required: true },
  { question_text: "Undigested food in stool", section: "Debelo crijevo", category: "large_intestine", order_index: 121, question_type: "symptom_0_3", is_required: true },
  { question_text: "Three or more large bowel movements daily", section: "Debelo crijevo", category: "large_intestine", order_index: 122, question_type: "symptom_0_3", is_required: true },
  { question_text: "Rectal itching", section: "Debelo crijevo", category: "large_intestine", order_index: 123, question_type: "symptom_0_3", is_required: true },
  { question_text: "Less than one bowel movement per day", section: "Debelo crijevo", category: "large_intestine", order_index: 124, question_type: "symptom_0_3", is_required: true },
  { question_text: "Foul smelling stools", section: "Debelo crijevo", category: "large_intestine", order_index: 125, question_type: "symptom_0_3", is_required: true },
  { question_text: "Cramping in lower abdomen", section: "Debelo crijevo", category: "large_intestine", order_index: 126, question_type: "symptom_0_3", is_required: true },
  { question_text: "Belching or intestinal gas within one hour after eating", section: "Debelo crijevo", category: "large_intestine", order_index: 127, question_type: "symptom_0_3", is_required: true },
  { question_text: "Mucus or blood in stool", section: "Debelo crijevo", category: "large_intestine", order_index: 128, question_type: "symptom_0_3", is_required: true },
  { question_text: "Bad breath/Halitosis", section: "Debelo crijevo", category: "large_intestine", order_index: 129, question_type: "symptom_0_3", is_required: true },
  { question_text: "Coated tongue", section: "Debelo crijevo", category: "large_intestine", order_index: 130, question_type: "symptom_0_3", is_required: true },
  { question_text: "Bitter taste in mouth", section: "Debelo crijevo", category: "large_intestine", order_index: 131, question_type: "symptom_0_3", is_required: true },
  { question_text: "Easily nauseated", section: "Debelo crijevo", category: "large_intestine", order_index: 132, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nausea when taking supplements", section: "Debelo crijevo", category: "large_intestine", order_index: 133, question_type: "symptom_0_3", is_required: true },
  { question_text: "Hemorrhoids", section: "Debelo crijevo", category: "large_intestine", order_index: 134, question_type: "symptom_0_3", is_required: true },
  { question_text: "Mucus in stools", section: "Debelo crijevo", category: "large_intestine", order_index: 135, question_type: "symptom_0_3", is_required: true },

  // Mineral Needs (Questions 136-164, 29 questions)
  { question_text: "Crave salt", section: "Potrebe za mineralima", category: "minerals", order_index: 136, question_type: "symptom_0_3", is_required: true },
  { question_text: "Leg cramps at rest", section: "Potrebe za mineralima", category: "minerals", order_index: 137, question_type: "symptom_0_3", is_required: true },
  { question_text: "Muscle cramps with exercise", section: "Potrebe za mineralima", category: "minerals", order_index: 138, question_type: "symptom_0_3", is_required: true },
  { question_text: "Frequent muscle spasms anywhere in body", section: "Potrebe za mineralima", category: "minerals", order_index: 139, question_type: "symptom_0_3", is_required: true },
  { question_text: "Muscle twitches", section: "Potrebe za mineralima", category: "minerals", order_index: 140, question_type: "symptom_0_3", is_required: true },
  { question_text: "Feeling wired or jittery after drinking coffee", section: "Potrebe za mineralima", category: "minerals", order_index: 141, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty staying asleep", section: "Potrebe za mineralima", category: "minerals", order_index: 142, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty falling asleep", section: "Potrebe za mineralima", category: "minerals", order_index: 143, question_type: "symptom_0_3", is_required: true },
  { question_text: "Headaches with exertion or stress", section: "Potrebe za mineralima", category: "minerals", order_index: 144, question_type: "symptom_0_3", is_required: true },
  { question_text: "Back ache", section: "Potrebe za mineralima", category: "minerals", order_index: 145, question_type: "symptom_0_3", is_required: true },
  { question_text: "Constipation", section: "Potrebe za mineralima", category: "minerals", order_index: 146, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty relaxing/High strung", section: "Potrebe za mineralima", category: "minerals", order_index: 147, question_type: "symptom_0_3", is_required: true },
  { question_text: "Arthritic tendencies", section: "Potrebe za mineralima", category: "minerals", order_index: 148, question_type: "symptom_0_3", is_required: true },
  { question_text: "Kidney stones/Gall stones", section: "Potrebe za mineralima", category: "minerals", order_index: 149, question_type: "symptom_0_3", is_required: true },
  { question_text: "Premenstrual cramping", section: "Potrebe za mineralima", category: "minerals", order_index: 150, question_type: "symptom_0_3", is_required: true },
  { question_text: "Menstrual cramps", section: "Potrebe za mineralima", category: "minerals", order_index: 151, question_type: "symptom_0_3", is_required: true },
  { question_text: "Hysterectomy/Have had", section: "Potrebe za mineralima", category: "minerals", order_index: 152, question_type: "yes_no", is_required: true },
  { question_text: "Hard stools", section: "Potrebe za mineralima", category: "minerals", order_index: 153, question_type: "symptom_0_3", is_required: true },
  { question_text: "Infrequent bowel movements", section: "Potrebe za mineralima", category: "minerals", order_index: 154, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dental caries", section: "Potrebe za mineralima", category: "minerals", order_index: 155, question_type: "symptom_0_3", is_required: true },
  { question_text: "Insomnia", section: "Potrebe za mineralima", category: "minerals", order_index: 156, question_type: "symptom_0_3", is_required: true },
  { question_text: "Osteoporosis", section: "Potrebe za mineralima", category: "minerals", order_index: 157, question_type: "symptom_0_3", is_required: true },
  { question_text: "High blood pressure", section: "Potrebe za mineralima", category: "minerals", order_index: 158, question_type: "symptom_0_3", is_required: true },
  { question_text: "Loss of taste sensation or smell", section: "Potrebe za mineralima", category: "minerals", order_index: 159, question_type: "symptom_0_3", is_required: true },
  { question_text: "White spots on fingernails", section: "Potrebe za mineralima", category: "minerals", order_index: 160, question_type: "symptom_0_3", is_required: true },
  { question_text: "Stretch marks on skin", section: "Potrebe za mineralima", category: "minerals", order_index: 161, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty falling asleep", section: "Potrebe za mineralima", category: "minerals", order_index: 162, question_type: "symptom_0_3", is_required: true },
  { question_text: "Decreased tolerance to extremes of temperature", section: "Potrebe za mineralima", category: "minerals", order_index: 163, question_type: "symptom_0_3", is_required: true },
  { question_text: "Slow healing", section: "Potrebe za mineralima", category: "minerals", order_index: 164, question_type: "symptom_0_3", is_required: true },

  // Essential Fatty Acids (Questions 165-172, 8 questions)
  { question_text: "Cracked skin on heels or fingertips", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 165, question_type: "symptom_0_3", is_required: true },
  { question_text: "Stiff or painful joints in morning", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 166, question_type: "symptom_0_3", is_required: true },
  { question_text: "Alligator skin/Chicken skin on backs of arms", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 167, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dry hair or skin", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 168, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive ear wax production", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 169, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive thirst/Dehydration", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 170, question_type: "symptom_0_3", is_required: true },
  { question_text: "Brittle, easily frayed nails", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 171, question_type: "symptom_0_3", is_required: true },
  { question_text: "History of cardiovascular disease", section: "Esencijalne masne kiseline", category: "essential_fatty_acids", order_index: 172, question_type: "symptom_0_3", is_required: true },

  // Sugar Regulation (Questions 173-185, 13 questions)
  { question_text: "Crave sweets", section: "Regulacija šećera", category: "sugar_regulation", order_index: 173, question_type: "symptom_0_3", is_required: true },
  { question_text: "Binge/Cravings for sweets not relieved by eating them", section: "Regulacija šećera", category: "sugar_regulation", order_index: 174, question_type: "symptom_0_3", is_required: true },
  { question_text: "Must have sweets after meals", section: "Regulacija šećera", category: "sugar_regulation", order_index: 175, question_type: "symptom_0_3", is_required: true },
  { question_text: "Eating sweets does not relieve sugar cravings", section: "Regulacija šećera", category: "sugar_regulation", order_index: 176, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty eating in the morning", section: "Regulacija šećera", category: "sugar_regulation", order_index: 177, question_type: "symptom_0_3", is_required: true },
  { question_text: "Sleepy in afternoon", section: "Regulacija šećera", category: "sugar_regulation", order_index: 178, question_type: "symptom_0_3", is_required: true },
  { question_text: "Shaky if hungry", section: "Regulacija šećera", category: "sugar_regulation", order_index: 179, question_type: "symptom_0_3", is_required: true },
  { question_text: "Fatigue relieved by eating", section: "Regulacija šećera", category: "sugar_regulation", order_index: 180, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty losing weight", section: "Regulacija šećera", category: "sugar_regulation", order_index: 181, question_type: "symptom_0_3", is_required: true },
  { question_text: "Wake up in middle of night", section: "Regulacija šećera", category: "sugar_regulation", order_index: 182, question_type: "symptom_0_3", is_required: true },
  { question_text: "Easily agitated, nervous, or irritable", section: "Regulacija šećera", category: "sugar_regulation", order_index: 183, question_type: "symptom_0_3", is_required: true },
  { question_text: "Poor memory or forgetful", section: "Regulacija šećera", category: "sugar_regulation", order_index: 184, question_type: "symptom_0_3", is_required: true },
  { question_text: "Blurred vision", section: "Regulacija šećera", category: "sugar_regulation", order_index: 185, question_type: "symptom_0_3", is_required: true },

  // Vitamin Needs (Questions 186-212, 27 questions)
  { question_text: "Crave sweets", section: "Potrebe za vitaminima", category: "vitamins", order_index: 186, question_type: "symptom_0_3", is_required: true },
  { question_text: "Increased appetite", section: "Potrebe za vitaminima", category: "vitamins", order_index: 187, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty falling asleep", section: "Potrebe za vitaminima", category: "vitamins", order_index: 188, question_type: "symptom_0_3", is_required: true },
  { question_text: "Mood swings", section: "Potrebe za vitaminima", category: "vitamins", order_index: 189, question_type: "symptom_0_3", is_required: true },
  { question_text: "Loss of appetite", section: "Potrebe za vitaminima", category: "vitamins", order_index: 190, question_type: "symptom_0_3", is_required: true },
  { question_text: "Insomnia", section: "Potrebe za vitaminima", category: "vitamins", order_index: 191, question_type: "symptom_0_3", is_required: true },
  { question_text: "Restless leg syndrome", section: "Potrebe za vitaminima", category: "vitamins", order_index: 192, question_type: "symptom_0_3", is_required: true },
  { question_text: "Constipation", section: "Potrebe za vitaminima", category: "vitamins", order_index: 193, question_type: "symptom_0_3", is_required: true },
  { question_text: "Cracks or sores on sides of mouth", section: "Potrebe za vitaminima", category: "vitamins", order_index: 194, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dry flaky skin", section: "Potrebe za vitaminima", category: "vitamins", order_index: 195, question_type: "symptom_0_3", is_required: true },
  { question_text: "Eczema or psoriasis", section: "Potrebe za vitaminima", category: "vitamins", order_index: 196, question_type: "symptom_0_3", is_required: true },
  { question_text: "Oily skin", section: "Potrebe za vitaminima", category: "vitamins", order_index: 197, question_type: "symptom_0_3", is_required: true },
  { question_text: "Sun sensitivity", section: "Potrebe za vitaminima", category: "vitamins", order_index: 198, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive bruising", section: "Potrebe za vitaminima", category: "vitamins", order_index: 199, question_type: "symptom_0_3", is_required: true },
  { question_text: "Slow wound healing", section: "Potrebe za vitaminima", category: "vitamins", order_index: 200, question_type: "symptom_0_3", is_required: true },
  { question_text: "Bleeding gums", section: "Potrebe za vitaminima", category: "vitamins", order_index: 201, question_type: "symptom_0_3", is_required: true },
  { question_text: "Loose teeth", section: "Potrebe za vitaminima", category: "vitamins", order_index: 202, question_type: "symptom_0_3", is_required: true },
  { question_text: "Red or sore tongue", section: "Potrebe za vitaminima", category: "vitamins", order_index: 203, question_type: "symptom_0_3", is_required: true },
  { question_text: "Frequent infections", section: "Potrebe za vitaminima", category: "vitamins", order_index: 204, question_type: "symptom_0_3", is_required: true },
  { question_text: "Muscle weakness", section: "Potrebe za vitaminima", category: "vitamins", order_index: 205, question_type: "symptom_0_3", is_required: true },
  { question_text: "Bone or joint pain", section: "Potrebe za vitaminima", category: "vitamins", order_index: 206, question_type: "symptom_0_3", is_required: true },
  { question_text: "Poor night vision", section: "Potrebe za vitaminima", category: "vitamins", order_index: 207, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dry eyes", section: "Potrebe za vitaminima", category: "vitamins", order_index: 208, question_type: "symptom_0_3", is_required: true },
  { question_text: "Poor concentration", section: "Potrebe za vitaminima", category: "vitamins", order_index: 209, question_type: "symptom_0_3", is_required: true },
  { question_text: "Tingling in hands or feet", section: "Potrebe za vitaminima", category: "vitamins", order_index: 210, question_type: "symptom_0_3", is_required: true },
  { question_text: "Loss of balance", section: "Potrebe za vitaminima", category: "vitamins", order_index: 211, question_type: "symptom_0_3", is_required: true },
  { question_text: "Hyperactivity", section: "Potrebe za vitaminima", category: "vitamins", order_index: 212, question_type: "symptom_0_3", is_required: true },

  // Adrenals (Questions 213-238, 26 questions)
  { question_text: "Headaches", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 213, question_type: "symptom_0_3", is_required: true },
  { question_text: "Blurred vision", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 214, question_type: "symptom_0_3", is_required: true },
  { question_text: "Chronic fatigue or get drowsy often", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 215, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dizziness", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 216, question_type: "symptom_0_3", is_required: true },
  { question_text: "Crave salt", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 217, question_type: "symptom_0_3", is_required: true },
  { question_text: "Low blood pressure", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 218, question_type: "symptom_0_3", is_required: true },
  { question_text: "Weakness/Tired all the time", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 219, question_type: "symptom_0_3", is_required: true },
  { question_text: "Chronic low back pain/Sore low back", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 220, question_type: "symptom_0_3", is_required: true },
  { question_text: "Arthritic tendencies", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 221, question_type: "symptom_0_3", is_required: true },
  { question_text: "Afternoon headaches", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 222, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nervousness/Feel shaky", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 223, question_type: "symptom_0_3", is_required: true },
  { question_text: "Insomnia", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 224, question_type: "symptom_0_3", is_required: true },
  { question_text: "Inability to concentrate", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 225, question_type: "symptom_0_3", is_required: true },
  { question_text: "Crave candy or coffee in afternoons", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 226, question_type: "symptom_0_3", is_required: true },
  { question_text: "Fullness/Pressure in head", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 227, question_type: "symptom_0_3", is_required: true },
  { question_text: "Feel light-headed if stand up suddenly", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 228, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty maintaining manipulative adjustment", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 229, question_type: "symptom_0_3", is_required: true },
  { question_text: "Clench or grind teeth", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 230, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty losing weight/Difficulty gaining weight", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 231, question_type: "symptom_0_3", is_required: true },
  { question_text: "Cuts heal slowly", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 232, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nails won't grow", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 233, question_type: "symptom_0_3", is_required: true },
  { question_text: "Tendency to sprain ankles/Weak ankles", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 234, question_type: "symptom_0_3", is_required: true },
  { question_text: "Tendency to get hives", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 235, question_type: "symptom_0_3", is_required: true },
  { question_text: "Easily startled by noises", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 236, question_type: "symptom_0_3", is_required: true },
  { question_text: "Unable to stay asleep", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 237, question_type: "symptom_0_3", is_required: true },
  { question_text: "Excessive urination/Awaken during night to urinate", section: "Nadbubrežne žlijezde", category: "adrenals", order_index: 238, question_type: "symptom_0_3", is_required: true },

  // Pituitary (Questions 239-251, 13 questions)
  { question_text: "Increased thirst", section: "Hipofiza", category: "pituitary", order_index: 239, question_type: "symptom_0_3", is_required: true },
  { question_text: "Increased appetite and/or cravings", section: "Hipofiza", category: "pituitary", order_index: 240, question_type: "symptom_0_3", is_required: true },
  { question_text: "Failing eyesight", section: "Hipofiza", category: "pituitary", order_index: 241, question_type: "symptom_0_3", is_required: true },
  { question_text: "Headaches in forehead area", section: "Hipofiza", category: "pituitary", order_index: 242, question_type: "symptom_0_3", is_required: true },
  { question_text: "Decreased tolerance to cold", section: "Hipofiza", category: "pituitary", order_index: 243, question_type: "symptom_0_3", is_required: true },
  { question_text: "Decreased tolerance to heat", section: "Hipofiza", category: "pituitary", order_index: 244, question_type: "symptom_0_3", is_required: true },
  { question_text: "Decreased sex drive", section: "Hipofiza", category: "pituitary", order_index: 245, question_type: "symptom_0_3", is_required: true },
  { question_text: "Sudden weight gain", section: "Hipofiza", category: "pituitary", order_index: 246, question_type: "symptom_0_3", is_required: true },
  { question_text: "Sudden weight loss", section: "Hipofiza", category: "pituitary", order_index: 247, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty gaining weight", section: "Hipofiza", category: "pituitary", order_index: 248, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty losing weight", section: "Hipofiza", category: "pituitary", order_index: 249, question_type: "symptom_0_3", is_required: true },
  { question_text: "Menstrual disorders", section: "Hipofiza", category: "pituitary", order_index: 250, question_type: "symptom_0_3", is_required: true },
  { question_text: "Memory disturbances", section: "Hipofiza", category: "pituitary", order_index: 251, question_type: "symptom_0_3", is_required: true },

  // Thyroid (Questions 252-267, 16 questions)
  { question_text: "Easily fatigued/Sluggish", section: "Štitnjača", category: "thyroid", order_index: 252, question_type: "symptom_0_3", is_required: true },
  { question_text: "Slow pulse rate/Low blood pressure", section: "Štitnjača", category: "thyroid", order_index: 253, question_type: "symptom_0_3", is_required: true },
  { question_text: "Constipation", section: "Štitnjača", category: "thyroid", order_index: 254, question_type: "symptom_0_3", is_required: true },
  { question_text: "Poor circulation", section: "Štitnjača", category: "thyroid", order_index: 255, question_type: "symptom_0_3", is_required: true },
  { question_text: "Difficulty losing weight", section: "Štitnjača", category: "thyroid", order_index: 256, question_type: "symptom_0_3", is_required: true },
  { question_text: "Dry or coarse skin", section: "Štitnjača", category: "thyroid", order_index: 257, question_type: "symptom_0_3", is_required: true },
  { question_text: "Intolerance to cold", section: "Štitnjača", category: "thyroid", order_index: 258, question_type: "symptom_0_3", is_required: true },
  { question_text: "Morning headaches that wear off as day progresses", section: "Štitnjača", category: "thyroid", order_index: 259, question_type: "symptom_0_3", is_required: true },
  { question_text: "Thinning of hair on scalp, face or genitals", section: "Štitnjača", category: "thyroid", order_index: 260, question_type: "symptom_0_3", is_required: true },
  { question_text: "Drying/breaking hair", section: "Štitnjača", category: "thyroid", order_index: 261, question_type: "symptom_0_3", is_required: true },
  { question_text: "Loss of lateral third of eyebrow", section: "Štitnjača", category: "thyroid", order_index: 262, question_type: "symptom_0_3", is_required: true },
  { question_text: "Frequent infections", section: "Štitnjača", category: "thyroid", order_index: 263, question_type: "symptom_0_3", is_required: true },
  { question_text: "Nervousness or tremors", section: "Štitnjača", category: "thyroid", order_index: 264, question_type: "symptom_0_3", is_required: true },
  { question_text: "Heart palpitations", section: "Štitnjača", category: "thyroid", order_index: 265, question_type: "symptom_0_3", is_required: true },
  { question_text: "Inward trembling", section: "Štitnjača", category: "thyroid", order_index: 266, question_type: "symptom_0_3", is_required: true },
  { question_text: "Increased pulse rate even at rest", section: "Štitnjača", category: "thyroid", order_index: 267, question_type: "symptom_0_3", is_required: true },

  // Cardiovascular (Questions 268-277, 10 questions)
  { question_text: "Aware of breathing heavily", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 268, question_type: "symptom_0_3", is_required: true },
  { question_text: "Aware of heart beating", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 269, question_type: "symptom_0_3", is_required: true },
  { question_text: "Chest pains", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 270, question_type: "symptom_0_3", is_required: true },
  { question_text: "Cough", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 271, question_type: "symptom_0_3", is_required: true },
  { question_text: "Irregular heart beat", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 272, question_type: "symptom_0_3", is_required: true },
  { question_text: "Heart palpitations", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 273, question_type: "symptom_0_3", is_required: true },
  { question_text: "High blood pressure", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 274, question_type: "symptom_0_3", is_required: true },
  { question_text: "Pain radiating into left arm/Angina", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 275, question_type: "symptom_0_3", is_required: true },
  { question_text: "Shortness of breath", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 276, question_type: "symptom_0_3", is_required: true },
  { question_text: "Swollen ankles", section: "Kardiovaskularni sustav", category: "cardiovascular", order_index: 277, question_type: "symptom_0_3", is_required: true },

  // Kidneys and Bladder (Questions 278-282, 5 questions)
  { question_text: "Burning or difficulty urinating", section: "Bubrezi i mjehur", category: "kidneys_bladder", order_index: 278, question_type: "symptom_0_3", is_required: true },
  { question_text: "Crave salt", section: "Bubrezi i mjehur", category: "kidneys_bladder", order_index: 279, question_type: "symptom_0_3", is_required: true },
  { question_text: "History of kidney stones", section: "Bubrezi i mjehur", category: "kidneys_bladder", order_index: 280, question_type: "symptom_0_3", is_required: true },
  { question_text: "Pain or ache in mid to lower back", section: "Bubrezi i mjehur", category: "kidneys_bladder", order_index: 281, question_type: "symptom_0_3", is_required: true },
  { question_text: "Night time urination", section: "Bubrezi i mjehur", category: "kidneys_bladder", order_index: 282, question_type: "symptom_0_3", is_required: true },

  // Male Health (Questions 283-291, 9 questions)
  { question_text: "Difficulty achieving or maintaining erection", section: "Samo za muškarce", category: "male_health", order_index: 283, question_type: "symptom_0_3", is_required: false },
  { question_text: "Urinary dribbling", section: "Samo za muškarce", category: "male_health", order_index: 284, question_type: "symptom_0_3", is_required: false },
  { question_text: "Increased nighttime urination", section: "Samo za muškarce", category: "male_health", order_index: 285, question_type: "symptom_0_3", is_required: false },
  { question_text: "Difficulty starting urination", section: "Samo za muškarce", category: "male_health", order_index: 286, question_type: "symptom_0_3", is_required: false },
  { question_text: "Decreased force of urination", section: "Samo za muškarce", category: "male_health", order_index: 287, question_type: "symptom_0_3", is_required: false },
  { question_text: "Decreased sex drive", section: "Samo za muškarce", category: "male_health", order_index: 288, question_type: "symptom_0_3", is_required: false },
  { question_text: "Difficulty achieving orgasm", section: "Samo za muškarce", category: "male_health", order_index: 289, question_type: "symptom_0_3", is_required: false },
  { question_text: "Breast enlargement or tenderness", section: "Samo za muškarce", category: "male_health", order_index: 290, question_type: "symptom_0_3", is_required: false },
  { question_text: "Hair loss on legs, breast, or arms", section: "Samo za muškarce", category: "male_health", order_index: 291, question_type: "symptom_0_3", is_required: false },

  // Female Health (Questions 292-311, 20 questions)
  { question_text: "Painful menstrual periods (cramps)", section: "Samo za žene", category: "female_health", order_index: 292, question_type: "symptom_0_3", is_required: false },
  { question_text: "Irregular menstrual cycle", section: "Samo za žene", category: "female_health", order_index: 293, question_type: "symptom_0_3", is_required: false },
  { question_text: "Heavy menstrual flow", section: "Samo za žene", category: "female_health", order_index: 294, question_type: "symptom_0_3", is_required: false },
  { question_text: "Scanty menstrual flow", section: "Samo za žene", category: "female_health", order_index: 295, question_type: "symptom_0_3", is_required: false },
  { question_text: "Clotting during menstruation", section: "Samo za žene", category: "female_health", order_index: 296, question_type: "symptom_0_3", is_required: false },
  { question_text: "PMS (Premenstrual syndrome)", section: "Samo za žene", category: "female_health", order_index: 297, question_type: "symptom_0_3", is_required: false },
  { question_text: "Menopausal hot flashes", section: "Samo za žene", category: "female_health", order_index: 298, question_type: "symptom_0_3", is_required: false },
  { question_text: "Vaginal dryness", section: "Samo za žene", category: "female_health", order_index: 299, question_type: "symptom_0_3", is_required: false },
  { question_text: "Breast tenderness", section: "Samo za žene", category: "female_health", order_index: 300, question_type: "symptom_0_3", is_required: false },
  { question_text: "Mood swings associated with cycle", section: "Samo za žene", category: "female_health", order_index: 301, question_type: "symptom_0_3", is_required: false },
  { question_text: "Water retention associated with cycle", section: "Samo za žene", category: "female_health", order_index: 302, question_type: "symptom_0_3", is_required: false },
  { question_text: "Anxious feelings", section: "Samo za žene", category: "female_health", order_index: 303, question_type: "symptom_0_3", is_required: false },
  { question_text: "Depression", section: "Samo za žene", category: "female_health", order_index: 304, question_type: "symptom_0_3", is_required: false },
  { question_text: "Fibrocystic breasts", section: "Samo za žene", category: "female_health", order_index: 305, question_type: "symptom_0_3", is_required: false },
  { question_text: "Difficulty losing weight", section: "Samo za žene", category: "female_health", order_index: 306, question_type: "symptom_0_3", is_required: false },
  { question_text: "Sweet cravings associated with cycle", section: "Samo za žene", category: "female_health", order_index: 307, question_type: "symptom_0_3", is_required: false },
  { question_text: "Facial hair growth", section: "Samo za žene", category: "female_health", order_index: 308, question_type: "symptom_0_3", is_required: false },
  { question_text: "Breast or ovarian cysts", section: "Samo za žene", category: "female_health", order_index: 309, question_type: "symptom_0_3", is_required: false },
  { question_text: "Endometriosis", section: "Samo za žene", category: "female_health", order_index: 310, question_type: "symptom_0_3", is_required: false },
  { question_text: "Low libido/Decreased sex drive", section: "Samo za žene", category: "female_health", order_index: 311, question_type: "symptom_0_3", is_required: false },

  // Immune System (Questions 312-321, 10 questions)
  { question_text: "Frequent or reoccurring infections", section: "Imunološki sustav", category: "immune", order_index: 312, question_type: "symptom_0_3", is_required: true },
  { question_text: "Chronic sore throat", section: "Imunološki sustav", category: "immune", order_index: 313, question_type: "symptom_0_3", is_required: true },
  { question_text: "Swollen lymph nodes in neck, underarm, or groin", section: "Imunološki sustav", category: "immune", order_index: 314, question_type: "symptom_0_3", is_required: true },
  { question_text: "Low grade fevers", section: "Imunološki sustav", category: "immune", order_index: 315, question_type: "symptom_0_3", is_required: true },
  { question_text: "History of chronic fatigue syndrome", section: "Imunološki sustav", category: "immune", order_index: 316, question_type: "symptom_0_3", is_required: true },
  { question_text: "Seasonal allergies or hay fever", section: "Imunološki sustav", category: "immune", order_index: 317, question_type: "symptom_0_3", is_required: true },
  { question_text: "Asthma/Difficulty breathing", section: "Imunološki sustav", category: "immune", order_index: 318, question_type: "symptom_0_3", is_required: true },
  { question_text: "Eczema or psoriasis", section: "Imunološki sustav", category: "immune", order_index: 319, question_type: "symptom_0_3", is_required: true },
  { question_text: "Hives", section: "Imunološki sustav", category: "immune", order_index: 320, question_type: "symptom_0_3", is_required: true },
  { question_text: "Autoimmune disease diagnosis", section: "Imunološki sustav", category: "immune", order_index: 321, question_type: "symptom_0_3", is_required: true },

  // Additional Open-Ended Question (Question 322)
  { question_text: "Molimo navedite bilo koje dodatne simptome, brige ili informacije koje želite podijeliti sa svojim terapeutom:", section: "Dodatna pitanja", category: "additional", order_index: 322, question_type: "long_text", is_required: false },
];
