// Complete NAQ Questionnaire - Full 321 questions dataset

export interface NAQQuestion {
  id: number;
  text: string;
  sectionName: string;
  scoringCategory: string;
  scoringWeight: number;
  questionType: 'scale_0_3' | 'yes_no' | 'multiple_choice';
  options?: string[];
}

export const NAQ_QUESTIONS: NAQQuestion[] = [
  // Nutrition Analysis (Part I) - Questions 1-20
  { id: 1, text: "Alkohol", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 2, text: "Umjetni zaslađivači", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 3, text: "Slatkiši, deserti, rafinirani šećer", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 4, text: "Gazirana pića", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 5, text: "Duhan za žvakanje", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 6, text: "Cigarete", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 7, text: "Cigare/lule", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 8, text: "Kofeinska pića", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 9, text: "Brza hrana", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 10, text: "Pržena hrana", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 11, text: "Suhomesnati proizvodi", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 12, text: "Margarin", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 13, text: "Mliječni proizvodi", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 14, text: "Izloženost zračenju", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "yes_no" },
  { id: 15, text: "Rafinirano brašno/pekarski proizvodi", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 16, text: "Vitamini i minerali", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 17, text: "Voda, destilirana", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 18, text: "Voda, iz slavine", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 19, text: "Voda, iz bunara", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 20, text: "Često na dijeti radi kontrole težine", sectionName: "Analiza prehrane", scoringCategory: "nutrition", scoringWeight: 1, questionType: "scale_0_3" },

  // Lifestyle Analysis (Part I) - Questions 21-24
  { id: 21, text: "Vježbanje tjedno", sectionName: "Analiza životnog stila", scoringCategory: "lifestyle", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 22, text: "Promjena posla", sectionName: "Analiza životnog stila", scoringCategory: "lifestyle", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 23, text: "Razvod", sectionName: "Analiza životnog stila", scoringCategory: "lifestyle", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 24, text: "Rad preko 60 sati tjedno", sectionName: "Analiza životnog stila", scoringCategory: "lifestyle", scoringWeight: 1, questionType: "scale_0_3" },

  // Medications (Part I) - Questions 25-51
  { id: 25, text: "Antacidi", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 26, text: "Lijekovi protiv anksioznosti", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 27, text: "Antibiotici", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 28, text: "Antikonvulzivi", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 29, text: "Antidepresivi", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 30, text: "Antifungici", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 31, text: "Aspirin/Ibuprofen", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 32, text: "Inhalatori za astmu", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 33, text: "Beta blokatori", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 34, text: "Kontracepcijske pilule/implantati", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 35, text: "Kemoterapija", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 36, text: "Lijekovi za snižavanje kolesterola", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 37, text: "Kortizon/steroidi", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 38, text: "Lijekovi za dijabetes/inzulin", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 39, text: "Diuretici", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 40, text: "Estrogen/progesteron (farmaceutski)", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 41, text: "Estrogen/progesteron (prirodni)", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 42, text: "Lijekovi za srce", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 43, text: "Lijekovi za visoki krvni tlak", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 44, text: "Laksativi", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 45, text: "Rekreativne droge", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 46, text: "Sredstva za opuštanje/spavanje", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 47, text: "Testosteron", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 48, text: "Lijekovi za štitnjaču", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 49, text: "Acetaminofen (Tylenol)", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 50, text: "Lijekovi za čir", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 51, text: "Sildenafil citrat (Viagra)", sectionName: "Lijekovi", scoringCategory: "medications", scoringWeight: 1, questionType: "scale_0_3" },

  // Upper Gastrointestinal System - Questions 52-70
  { id: 52, text: "Podrigivanje ili plinovi unutar sat vremena nakon jela", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 53, text: "Žgaravica ili refluks kiseline", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 54, text: "Nadutost unutar sat vremena nakon jela", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 55, text: "Veganska prehrana (bez mliječnih proizvoda, mesa, ribe ili jaja)", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "yes_no" },
  { id: 56, text: "Loš zadah (halitoza)", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 57, text: "Gubitak okusa za meso", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 58, text: "Znoj ima jak miris", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 59, text: "Želudac uznemiren uzimanjem vitamina", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 60, text: "Osjećaj prekomjerne punoće nakon jela", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 61, text: "Osjećaj da biste preskočili doručak", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 62, text: "Osjećate se bolje ako ne jedete", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 63, text: "Pospanost nakon jela", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 64, text: "Nokti se lako lome, ljušte ili pucaju", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 65, text: "Anemija koja ne reagira na željezo", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 66, text: "Bolovi ili grčevi u želucu", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 67, text: "Kronični proljev", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 68, text: "Proljev ubrzo nakon jela", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 69, text: "Crna ili katranasta stolica", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 70, text: "Neprobavljena hrana u stolici", sectionName: "Gornji gastrointestinalni sustav", scoringCategory: "upper_gi", scoringWeight: 1, questionType: "scale_0_3" },

  // Liver & Gallbladder - Questions 71-98
  { id: 71, text: "Bol između lopatica", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 72, text: "Želudac uznemiren masnom hranom", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 73, text: "Masna ili sjajna stolica", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 74, text: "Mučnina", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 75, text: "Mučnina u vožnji (more, automobil, avion)", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 76, text: "Povijest jutarnjih mučnina", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 77, text: "Svijetla ili glinena stolica", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 78, text: "Suha koža, svrbež stopala ili ljuštenje kože na stopalima", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 79, text: "Glavobolja iznad očiju", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 80, text: "Napadi žučnog mjehura", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "Prije više godina", "Unutar zadnje godine", "Unutar zadnja 3 mjeseca"] },
  { id: 81, text: "Uklonjen žučni mjehur", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 82, text: "Gorak okus u ustima, posebno nakon jela", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 83, text: "Pozlilo bi vam da popijete vino", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 84, text: "Lako se opijete ako biste popili vino", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 85, text: "Lako vas uhvati mamurluk ako biste popili vino", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 86, text: "Konzumacija alkohola tjedno", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "multiple_choice", options: ["<3 pića", "<7 pića", "<14 pića", ">14 pića"] },
  { id: 87, text: "Liječeni alkoholičar", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 88, text: "Povijest zlouporabe droga ili alkohola", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 89, text: "Povijest hepatitisa", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 90, text: "Dugotrajna upotreba lijekova na recept/rekreativnih droga", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "yes_no" },
  { id: 91, text: "Osjetljivost na kemikalije (parfemi, sredstva za čišćenje, itd.)", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 92, text: "Osjetljivost na duhanski dim", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 93, text: "Izloženost ispušnim plinovima dizela", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 94, text: "Bol ispod desnog rebrenog luka", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 95, text: "Hemoroidi ili proširene vene", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 96, text: "Konzumacija NutraSweet (aspartama)", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 97, text: "Osjetljivost na NutraSweet (aspartam)", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 98, text: "Kronični umor ili fibromialgija", sectionName: "Jetra i žučni mjehur", scoringCategory: "liver_gallbladder", scoringWeight: 1, questionType: "scale_0_3" },

  // Small Intestine - Questions 99-115
  { id: 99, text: "Alergije na hranu", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 100, text: "Nadutost trbuha 1 do 2 sata nakon jela", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 101, text: "Određena hrana vas čini umornima ili nadutima", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "yes_no" },
  { id: 102, text: "Puls se ubrzava nakon jela", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 103, text: "Alergije iz zraka", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 104, text: "Imate koprivnjaču", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 105, text: "Kongestija sinusa, \"začepljena glava\"", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 106, text: "Žudnja za kruhom ili tjesteninom", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 107, text: "Izmjenični zatvor i proljev", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 108, text: "Crohnova bolest", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Trenutno blago stanje", "Teško"] },
  { id: 109, text: "Osjetljivost na pšenicu ili žitarice", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 110, text: "Osjetljivost na mliječne proizvode", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 111, text: "Postoji li hrana koje se ne biste mogli odreći", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "yes_no" },
  { id: 112, text: "Astma, infekcije sinusa, začepljen nos", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 113, text: "Bizarni živopisni snovi, noćne more", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 114, text: "Žudnja za slatkim ili mučnim za vrijeme menstruacije", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 115, text: "Kandidijaza ili Candida", sectionName: "Tanko crijevo", scoringCategory: "small_intestine", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Blago", "Umjereno", "Jako"] },

  // Large Intestine/Colon - Questions 116-139
  { id: 116, text: "Zapor", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 117, text: "Proljev", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 118, text: "Imate stolicu manju od jednom dnevno", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 119, text: "Odlazak na WC tri ili više puta dnevno", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 120, text: "Potrebno je napinjanje za stolicu", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 121, text: "Mišićne bolesti ili napetost", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 122, text: "Intestinalni plinovi ili nadutost", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 123, text: "Krv u stolici", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 124, text: "Sluz u stolici", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 125, text: "Žgaravica ili refluks kiseline", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 126, text: "Glavobolje", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 127, text: "Sklonost sinuzitisu", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 128, text: "Gorak ili metalik okus u ustima", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 129, text: "Teško se probuditi ujutro", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 130, text: "Smrad tijela", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 131, text: "Loš zadah (halitoza)", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 132, text: "Upotreba klistirova ili laksativa", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "Mjesečno", "Tjedno", "Dnevno"] },
  { id: 133, text: "Ulcerozni kolitis", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 134, text: "Sindrom iritabilnog crijeva", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 135, text: "Čirevi u ustima", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 136, text: "Koža se lako poderotine", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 137, text: "Lako krijete modrice", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 138, text: "Varikozne vene", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 139, text: "Hemoroidi", sectionName: "Debelo crijevo", scoringCategory: "large_intestine", scoringWeight: 1, questionType: "scale_0_3" },

  // Kidney & Adrenal - Questions 140-179
  { id: 140, text: "Bol u donjem dijelu leđa", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 141, text: "Česti ili hitni poriv za mokrenjem", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 142, text: "Premokreno krevete nakon 3. godine", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "yes_no" },
  { id: 143, text: "Mokrite manje od 3 puta dnevno", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 144, text: "Mokrite više od 6 puta dnevno", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 145, text: "Bol ili pečenje pri mokri", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 146, text: "Teško počinjanje mokri", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 147, text: "Buđenje se tokom noći za mokrenje", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 148, text: "Mutan ili žuti urin", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 149, text: "Kamenci u bubrezima ili mokraćnim kanalima", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "Prije više godina", "Unutar zadnje godine", "Ponovno"] },
  { id: 150, text: "Infekcije mokraćnog sustava", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "Prije više godina", "Unutar zadnje godine", "Češće"] },
  { id: 151, text: "Visoki krvni tlak", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "Granično", "Visok", "Jako visok"] },
  { id: 152, text: "Niski krvni tlak", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "Granično", "Nizak", "Jako nizak"] },
  { id: 153, text: "Vrtoglavica ili nesvjestice kad se brzo ustanete", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 154, text: "Prisiljeni ste sjediti ili spustiti glavu da se ne onesvijestite", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 155, text: "Lice otiče, posebno oko očiju", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 156, text: "Ruke ili noge vam otiekaju", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 157, text: "Koža jaukva nakon vježbanja", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 158, text: "Krvna slika pokazuje kalij iznad ili ispod normale", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 159, text: "Krvna slika pokazuje natrij iznad ili ispod normale", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 160, text: "Osjetljiv na sjajno sunce ili reflektirajuću svjetlost", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 161, text: "Stres utječe na vaše zdravlje", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 162, text: "Teško se opuštate", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 163, text: "Osjećate se treskavih ili nervozni", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 164, text: "Imate osjećaj kao da ćete se onesvijestiti ako preskočite obrok", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 165, text: "Žudnja za soli", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 166, text: "Crne kružnice oko očiju", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 167, text: "Kronični umor", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 168, text: "Smanjenna tolerancija na stres", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 169, text: "Smanjena energija", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 170, text: "Teško se ustajete ujutro", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 171, text: "Treba vam kava za početak", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 172, text: "Poteškoće s razmišljanjem prije 10 ujutro", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 173, text: "Pamćenje ili koncentracija nisu oštra kao nekada", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 174, text: "Energija popada tijekom dana", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 175, text: "Najvjerniji ste navečer, nakon 6", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 176, text: "Energija se pojavljuje nakon večere", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 177, text: "Često budni između 1 i 4 ujutro", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 178, text: "Koristite \"energetske stimulanse\" (kavu, čaj, gazirana pića)", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 179, text: "Teško gubite weight čak i dijetom", sectionName: "Bubrezi i nadbubrežne žlijezde", scoringCategory: "kidney_adrenal", scoringWeight: 1, questionType: "scale_0_3" },

  // Heart & Lungs - Questions 180-208
  { id: 180, text: "Bol u prsima", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 181, text: "Nepravilan rad srca ili preskakanje otkucaja", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 182, text: "Brz puls ili tahikardija", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 183, text: "Visoki krvni tlak", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 184, text: "Nizak krvni tlak", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 185, text: "Kratkoća daha", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 186, text: "Kronična zastoj ili kašalj", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 187, text: "Kašalj ili sluz", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 188, text: "Žut ili zelenu sluz", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 189, text: "Kronična bronhitis", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 190, text: "Emfizem", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 191, text: "Pneumonija", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "Prije više godina", "Unutar zadnje godine", "Reakurentno"] },
  { id: 192, text: "Astma", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "U prošlosti", "Umjereno", "Jako"] },
  { id: 193, text: "Seno groznica ili ostale dišne alergije", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 194, text: "Eksžema", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 195, text: "Druge kožne smetnje", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 196, text: "Suha koža", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 197, text: "Suha, lomljiva kosa", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 198, text: "Slaba cirkulacija", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 199, text: "Varikozne vene", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 200, text: "Povijes srčanjih problem u obitelji", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "yes_no" },
  { id: 201, text: "Otišavanja u licu", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 202, text: "Otišavanja u gležnjevima ili stopalima", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 203, text: "Hladno tijelo, ruke ili noge", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 204, text: "Visok kolesterol (>200)", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "multiple_choice", options: ["<200", "200-240", "240-300", ">300"] },
  { id: 205, text: "Visoki triglyceridi (>150)", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "multiple_choice", options: ["<150", "150-200", "200-300", ">300"] },
  { id: 206, text: "Koristite lijekove za kolesterol", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "yes_no" },
  { id: 207, text: "Napadi panike", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 208, text: "Osjećate se kao da se gušite", sectionName: "Srce i pluća", scoringCategory: "heart_lungs", scoringWeight: 1, questionType: "scale_0_3" },

  // Brain & Nervous System - Questions 209-258
  { id: 209, text: "Glavobolje", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 210, text: "Migrene", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 211, text: "Vrtoglavica", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 212, text: "Nesvjestice", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 213, text: "Napadaji", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "multiple_choice", options: ["Nikad", "U djetinjstvu", "Prije više godina", "Nedavno"] },
  { id: 214, text: "Tremor u rukama", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 215, text: "Trinjenje u rukama ili nogama", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 216, text: "Utrnulost u rukama ili nogama", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 217, text: "Slabost na jednoj strani tijela", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 218, text: "Poteškoće s govorom", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 219, text: "Gubitak koordinacije", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 220, text: "Problemi s vidjem", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 221, text: "Dvostruko vidjenje", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 222, text: "Zamućeno viđenje", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 223, text: "Sjene u vidnom polju", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 224, text: "Problemi sa sluhom", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 225, text: "Zujanje u ušima", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 226, text: "Problemi s ravnotežom", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 227, text: "Moj Mozak se osjeća \"zamagljenio\"", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 228, text: "Problemi s koncentracijom", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 229, text: "Problemi s pamćenjem", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 230, text: "Gubim misao u sredini rečenice", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 231, text: "Zaboravljam imena bliskih prijatelja", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 232, text: "Teško pronašti potrebnu riječ", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 233, text: "Teško rješavam probleme", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 234, text: "Teško učim nove informacije", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 235, text: "Postoji familiju povijest Alzheimera ili demenije", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "yes_no" },
  { id: 236, text: "Depresija", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 237, text: "Anksioznost ili zabrinutost", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 238, text: "Razdražljivost", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 239, text: "Promjene raspoloženja", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 240, text: "Osjećate li da se ljudi zalažu protiv vas", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 241, text: "Poteškoće u donošenju odluka", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 242, text: "Lako se plaših", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 243, text: "Buđenje se nervno ili uznemireno", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 244, text: "Teško se opuštate", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 245, text: "Teško zaspijete", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 246, text: "Često se budite tokom noći", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 247, text: "Ustan se često tired", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 248, text: "Nemte energije", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 249, text: "Seksualni nagon manji nego prije", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 250, text: "Problemi sa snom na ispitu ili u stresnim vremenima", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 251, text: "Previše razmišljate", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 252, text: "Teško prihvatite kritiku", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 253, text: "Žudnja za mučnim ili slatkim", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 254, text: "Teško Controlijrate svoju težinu", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 255, text: "Zavisni o određenim napicima (alkohol, kava itd.)", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 256, text: "Potrebno mi je \"nešto\" da porazum", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 257, text: "Pokretite se živčano (nervozno tapkanje, lupkanje)", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 258, text: "Koristite rekreativne droge", sectionName: "Mozak i živčani sustav", scoringCategory: "brain_nervous", scoringWeight: 1, questionType: "scale_0_3" },

  // Hormones - Questions 259-281
  { id: 259, text: "Premenstrualni sindrom", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "Umjereno", "Jako"] },
  { id: 260, text: "Zadržavanje vode", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 261, text: "Bolne ili ciste dojke", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 262, text: "Fibroadni tumori u dojci", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "U prošlosti", "Trenutno"] },
  { id: 263, text: "Fibromi u maternici", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "U prošlosti", "Trenutno"] },
  { id: 264, text: "Endometriosisa", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "U prošlosti", "Trenutno"] },
  { id: 265, text: "Problem s ovulacijom", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "U prošlosti", "Trenutno"] },
  { id: 266, text: "Neplodnost", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "U prošlosti", "Trenutno"] },
  { id: 267, text: "Pobačaj", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "Jednom", "Višestruko"] },
  { id: 268, text: "Nedostatak menstruacije", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 269, text: "Obilna menstruacija", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 270, text: "Kratkih ili dugih ciklusi", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 271, text: "Neregularne menstruacija", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 272, text: "Bolne menstruacija", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 273, text: "Rast dlaka na licu ili tijelu", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 274, text: "Promjena glasa", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 275, text: "Postmenopauzalni problemi", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "Umjereno", "Jako"] },
  { id: 276, text: "Valovi vručine", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 277, text: "Noćno znojenje", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 278, text: "Vaginal dryness", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 279, text: "Smanjeni libido", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 280, text: "Problem s prostatom", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "multiple_choice", options: ["N/A", "Nikad", "Umjereno", "Jako"] },
  { id: 281, text: "Erektilna disfunkcija", sectionName: "Hormoni", scoringCategory: "hormones", scoringWeight: 1, questionType: "scale_0_3" },

  // Immune System - Questions 282-302
  { id: 282, text: "Česti prezeb ili grip", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 283, text: "Česte infekcije", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 284, text: "Sporo cijeljenje rana", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 285, text: "Nedostatak energije", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 286, text: "Kronični umor", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 287, text: "Povećane žlijezde", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 288, text: "Česte upale grla", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 289, text: "Febrina pęknięcia ili herpez", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 290, text: "Česti ukratki", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 291, text: "Reumatoidni artritis", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 292, text: "Lupus", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 293, text: "Multipla skleroza", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "multiple_choice", options: ["Ne", "U prošlosti", "Umjereno", "Jako"] },
  { id: 294, text: "Ostala autoimuna bolest", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 295, text: "Željena ili neočekivana promjena weight", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 296, text: "Nedostatak apetita", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 297, text: "Sklonost prejedanje", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 298, text: "Kožni problem", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 299, text: "Koža lako izgori na suncu", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 300, text: "Koža sporije tamni na suncu", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 301, text: "Sjene ili mrlje na koži", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 302, text: "Familiju povijest cancer", sectionName: "Imunni sustav", scoringCategory: "immune", scoringWeight: 1, questionType: "yes_no" },

  // Lifestyle Analysis (Part II) - Questions 303-321
  { id: 303, text: "Otišao ste na 8 sati spavanja po noći", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 304, text: "Ustajete se osvježeni", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 305, text: "Jeste li zadovoljni sa vašim posoom", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 306, text: "Osjećate li se prijećinoma u odnosu", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 307, text: "Jeste li zadovoljni svojim socijalnim životom", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 308, text: "Percipirate li da imate adkevtnu emotionalnu podršku", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 309, text: "Imate li religijske or pairitual vjerovanje", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 310, text: "Jeste li zadovoljni sa svojom življenjem genralno", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 311, text: "Smejete li se i zabavljate frequently", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 312, text: "Frequent perceptions negativnih emotions (stres, anxnost, ljuteen)", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 313, text: "Cviating death ili major traume u zadnje 2 godine", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 314, text: "Experienced majoran životnu promjenu (braka, razvods, seliba) u zadnje 2 godine", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 315, text: "Financijski problem u zadnjih 2 godine", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 316, text: "Legal problem u zadnjih 2 godine", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 317, text: "Experienced domestic violence ili trauma", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 318, text: "Tečajevi se s chronic bolesće ili stanjem", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 319, text: "Mislite da ste općenito zdrava osoba", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 320, text: "Other health problems ne covered boove", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" },
  { id: 321, text: "Opći koment ili brige vezane za vaše zdravlje", sectionName: "Analiza životnog stila (dio II)", scoringCategory: "lifestyle_2", scoringWeight: 1, questionType: "scale_0_3" }
];