// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akywynddwcxzrkotewtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreXd5bmRkd2N4enJrb3Rld3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTc2MDgsImV4cCI6MjA2OTg5MzYwOH0.eyJpv_erN7OykJKVgmRi_vymETiD3CysmuHfaQFaZB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});